export const restaurants = [
  {
    name: "The Spicy Bistro",
    type: "Mexican",
    rating: 4.2,
    deliveryTime: 40,
    discount: 20,
    startingPrice: 150,
    followWHOProtocol: true,
    imageUrl: "/The-Chef-Thali-Wala.png",
  },
  {
    name: "Sushi Palace",
    type: "Japanese",
    rating: 4.5,
    deliveryTime: 30,
    discount: 10,
    startingPrice: 200,
    followWHOProtocol: true,
    imageUrl: "/new-pizza-king.png",
  },
  {
    name: "The Grill House",
    type: "American",
    rating: 4.0,
    deliveryTime: 45,
    discount: 15,
    startingPrice: 180,
    followWHOProtocol: false,
    imageUrl: "/kwality-icecream.png",
  },
  {
    name: "Curry Corner",
    type: "Indian",
    rating: 3.8,
    deliveryTime: 35,
    discount: 25,
    startingPrice: 120,
    followWHOProtocol: true,
    imageUrl: "/lunchbox-meals.png",
  },
  {
    name: "Pizza Paradise",
    type: "Italian",
    rating: 4.3,
    deliveryTime: 25,
    discount: 30,
    startingPrice: 250,
    followWHOProtocol: true,
    imageUrl: "/pinoz-pizza.png",
  },
  {
    name: "The Noodle Bar",
    type: "Chinese",
    rating: 4.1,
    deliveryTime: 40,
    discount: 20,
    startingPrice: 160,
    followWHOProtocol: false,
    imageUrl: "/chetan-kitchen.png",
  },
  {
    name: "Mediterranean Delights",
    type: "Mediterranean",
    rating: 4.4,
    deliveryTime: 35,
    discount: 10,
    startingPrice: 190,
    followWHOProtocol: true,
    imageUrl: "/The-Chef-Thali-Wala.png",
  },
  {
    name: "The Vegan Spot",
    type: "Vegan",
    rating: 4.6,
    deliveryTime: 50,
    discount: 15,
    startingPrice: 180,
    followWHOProtocol: true,
    imageUrl: "/new-pizza-king.png",
  },
  {
    name: "Tandoori Flavors",
    type: "Indian",
    rating: 4.0,
    deliveryTime: 30,
    discount: 25,
    startingPrice: 150,
    followWHOProtocol: true,
    imageUrl: "/kwality-icecream.png",
  },
  {
    name: "Burger Joint",
    type: "American",
    rating: 4.2,
    deliveryTime: 20,
    discount: 30,
    startingPrice: 170,
    followWHOProtocol: false,
    imageUrl: "/lunchbox-meals.png",
  },
  {
    name: "Thai Fusion",
    type: "Thai",
    rating: 4.3,
    deliveryTime: 45,
    discount: 20,
    startingPrice: 220,
    followWHOProtocol: true,
    imageUrl: "/pinoz-pizza.png",
  },
  {
    name: "The Pasta Place",
    type: "Italian",
    rating: 4.1,
    deliveryTime: 35,
    discount: 15,
    startingPrice: 190,
    followWHOProtocol: true,
    imageUrl: "/chetan-kitchen.png",
  },
  {
    name: "Burrito Bonanza",
    type: "Mexican",
    rating: 4.4,
    deliveryTime: 40,
    discount: 25,
    startingPrice: 160,
    followWHOProtocol: false,
    imageUrl: "/The-Chef-Thali-Wala.png",
  },
  {
    name: "Wok Master",
    type: "Chinese",
    rating: 4.2,
    deliveryTime: 30,
    discount: 30,
    startingPrice: 170,
    followWHOProtocol: true,
    imageUrl: "/new-pizza-king.png",
  },
  {
    name: "Seafood Sensation",
    type: "Seafood",
    rating: 4.3,
    deliveryTime: 25,
    discount: 10,
    startingPrice: 250,
    followWHOProtocol: true,
    imageUrl: "/kwality-icecream.png",
  },
  {
    name: "The Grill Shack",
    type: "American",
    rating: 4.0,
    deliveryTime: 35,
    discount: 15,
    startingPrice: 180,
    followWHOProtocol: true,
    imageUrl: "/lunchbox-meals.png",
  },
  {
    name: "Sushi Central",
    type: "Japanese",
    rating: 4.5,
    deliveryTime: 40,
    discount: 20,
    startingPrice: 200,
    followWHOProtocol: false,
    imageUrl: "/pinoz-pizza.png",
  },
  {
    name: "Spice of India",
    type: "Indian",
    rating: 3.9,
    deliveryTime: 30,
    discount: 25,
    startingPrice: 150,
    followWHOProtocol: true,
    imageUrl: "/chetan-kitchen.png",
  },
  {
    name: "Pizzeria Italia",
    type: "Italian",
    rating: 4.2,
    deliveryTime: 25,
    discount: 30,
    startingPrice: 190,
    followWHOProtocol: true,
    imageUrl: "/The-Chef-Thali-Wala.png",
  },
  {
    name: "Dragon Delight",
    type: "Chinese",
    rating: 4.4,
    deliveryTime: 35,
    discount: 10,
    startingPrice: 160,
    followWHOProtocol: true,
    imageUrl: "/new-pizza-king.png",
  },
  {
    name: "Greek Gyro",
    type: "Mediterranean",
    rating: 4.3,
    deliveryTime: 40,
    discount: 15,
    startingPrice: 180,
    followWHOProtocol: false,
    imageUrl: "/kwality-icecream.png",
  },
  {
    name: "Vegan Vibes",
    type: "Vegan",
    rating: 4.6,
    deliveryTime: 50,
    discount: 20,
    startingPrice: 200,
    followWHOProtocol: true,
    imageUrl: "/lunchbox-meals.png",
  },
  {
    name: "Punjabi Dhaba",
    type: "Indian",
    rating: 4.1,
    deliveryTime: 30,
    discount: 25,
    startingPrice: 150,
    followWHOProtocol: true,
    imageUrl: "/pinoz-pizza.png",
  },
  {
    name: "The Burger Joint",
    type: "American",
    rating: 4.2,
    deliveryTime: 20,
    discount: 30,
    startingPrice: 170,
    followWHOProtocol: true,
    imageUrl: "/chetan-kitchen.png",
  },
  {
    name: "Pad Thai Palace",
    type: "Thai",
    rating: 4.3,
    deliveryTime: 45,
    discount: 20,
    startingPrice: 210,
    followWHOProtocol: false,
    imageUrl: "/The-Chef-Thali-Wala.png",
  },
  {
    name: "Bella Italia",
    type: "Italian",
    rating: 4.1,
    deliveryTime: 35,
    discount: 15,
    startingPrice: 190,
    followWHOProtocol: true,
    imageUrl: "/new-pizza-king.png",
  },
  {
    name: "Taco Time",
    type: "Mexican",
    rating: 4.4,
    deliveryTime: 40,
    discount: 25,
    startingPrice: 170,
    followWHOProtocol: true,
    imageUrl: "/kwality-icecream.png",
  },
  {
    name: "Wok N Roll",
    type: "Chinese",
    rating: 4.2,
    deliveryTime: 30,
    discount: 30,
    startingPrice: 180,
    followWHOProtocol: false,
    imageUrl: "/lunchbox-meals.png",
  },
];
