export const searchMoreFiltersOptions = [
  "Discounts",
  "Special Deals",
  "Promotions",
  "Limited Time Offers",
  "Flash Sales",
  "Exclusive Discounts",
  "Bargains",
  "Savings",
  "Clearance",
  "Hot Deals",
  "Irresistible Offers",
  "Big Discounts",
  "Sale Events",
  "Markdowns",
  "Doorbusters",
  "Best Prices",
  "Unbeatable Deals",
  "Value for Money",
  "Steep Discounts",
  "Massive Savings",
  "Lowest Prices",
];
